### ISSUE TITLE
Raw images using preview resolution

### ISSUE THREAD

**Issue by binarypickle** [Polarrco/polarr_chrome_web_support#22] opened 2016-11-13 18:15 UTC
I see that raw support is still listed as "experimental" in the chrome store, but wanted to make sure that the issue is posted. Raw files from a Sony A6000, so the ARW file format, seem to be importing/editing/exporting using the embedded preview rather than the full file. So instead of a 6000 x 4000 resolution, it is using a 1616 x 1080. Kind of a bummer. 

Attached a screenshot from Polarr and from Capture One (windows) of the same file with the resolution shown. For reference, I'm using an Asus Chromebook R13.

![polarr](https://cloud.githubusercontent.com/assets/1137022/20247757/70707cee-a99a-11e6-8432-d4ac3616366b.png)

![capture one](https://cloud.githubusercontent.com/assets/1137022/20247771/f8d20666-a99a-11e6-8a8a-5e18faeff38c.png)

**Comment by BirdyF** [comment] 2016-11-19 16:42
Yes. It is an important question for me too. I noticed this problem/limitation on Fuji X30 RAF files but in fact it seems to be a limitation for all the RAW file formats. 
Is this limitation valid on all the Polarr versions (Mac, Windows...) ?
I will be ready to pay some money to access to the raw files with their original resolution.

**Comment by RiTCHiE007NL** [comment] 2016-12-20 13:40
Did you change the export setting to the highest? Because when i load up my NEF (nikon RAW) to polarr it says the correct 6000x4000 size and even after exporting it has the same resolution.

**Comment by BirdyF** [comment] 2016-12-21 18:08
Personally I have this resolution problem with RAF format (Fujifilm X30 and XT-1). Using NEF (Nikon V1) resolution seems correct.
Please note that the problem is when loading the file (not exporting). Once the picture is loaded in Polarr I can see the resolution in the upper left (below the histogram). It is correct in JPEG and incorrect in RAF format.

**Comment by RiTCHiE007NL** [comment] 2016-12-23 13:28
Hi,

Yea i downloaded a sample ARW file and tried it in different version of polarr from like the web to windows app but you are indeed right so hope this gets fixed fast because its a big problem but i did try to convert the ARW to a DNG with the adobe tool and the outcome was still the same so i dont know if its a polarr problem or a sony problem.

**Comment by bwang29** [comment] 2016-12-29 19:42
Polarr for Chrome currently doesn't do full RAW decoding as it is a web app. The only real raw decoding we have is our Mac app. Closing issue.

**Closed by bwang29** 2016-12-29 19:43 UTC

**Comment by binarypickle** [comment] 2016-12-29 21:54
Well, ok. The point wasn't that it was a bug, but just an FYI with the hopes that we could get an idea of if / when it was going to be added to the roadmap. This would be a pretty solid feature to those of us who would love to do some editing with our chromebooks rather than lug around a macbook pro everywhere. . 

In the meantime, maybe putting some clarification on the listing in the chrome store would be helpful, as "Experimental support for most popular RAW formats" doesn't really explain what we should or shouldn't expect.

Thanks
